#!/bin/sh

# Use $XINITRC variable if file exists.
[ -f "$XINITRC" ] && alias startx="startx $XINITRC"

# sudo not required for some system commands
for command in mount umount sv pacman updatedb su shutdown poweroff reboot ; do
	alias $command="sudo $command"
done; unset command

# Verbosity and settings that you pretty much just always are going to want.
alias \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -vI" \
	bc="bc -ql" \
	mkd="mkdir -pv" \
	yt="youtube-dl --add-metadata -i" \
	yta="yt -x -f bestaudio/best" \
	ffmpeg="ffmpeg -hide_banner"

# Colorize commands when possible.
alias \
	ls="ls -hN --color=auto --group-directories-first" \
	la="ls -AN --color=auto --group-directories-first" \
	ll="ls -AlhN --color=auto --group-directories-first" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi"

# These common commands are just too long! Abbreviate them.

alias \
	ka="killall" \
	g="git" \
	bt="bluetoothctl" \
	sdn="sudo shutdown -h now" \
	e="$EDITOR" \
	se="sudo $EDITOR" \
	v="$EDITOR" \
	p="pacman" \
	x="sxiv" \
	z="zathura"

alias lf="lfub"

fe() { find $HOME/.config/* $HOME/.local/bin/* | grep -vi 'brave\|libre\|nvm' | fzf | xargs -r $EDITOR ;}	

alias \
	ref="shortcuts >/dev/null; source ${XDG_CONFIG_HOME:-$HOME/.config}/shell/shortcutrc ; source ${XDG_CONFIG_HOME:-$HOME/.config}/shell/zshnameddirrc" \
