#!/bin/sh
[[ -f ~/.config/zsh/.zshenv ]] && source ~/.config/zsh/.zshenv
[[ -f ~/.config/shell/profile ]] && source ~/.config/shell/profile

xsetroot -cursor_name left_ptr &
setupinput &		# run the `fixinput` script, switches caps and escape/super
# /usr/bin/pipewire &
# /usr/bin/pipewire-pulse &
# /usr/bin/pipewire-media-session &
/usr/bin/pulseaudio &


